/**
 * Sprint 1 — Agent runtime type definitions.
 *
 * The types in this file define the contract every agent must satisfy
 * (Agent, AgentInput, AgentOutput, AgentContext, HealthStatus), the
 * transport-spanning MessageBus abstraction, the typed AgentMessage
 * envelope that flows over the bus, and the AuditLogEntry shape that
 * gets persisted to ./logs/audit_*.log after every agent.run() call.
 *
 * Defaults (per sprint-contract.md open questions):
 *   - `Agent` is declared as a TypeScript `interface` (declaration-merging friendly).
 *   - `image_id` is a plain `string` (no branded type) for Sprint 1.
 *   - `HealthStatus` is a discriminated union:
 *       { ok: true;  latencyMs: number } | { ok: false; error: string }
 *   - `MessageBus.request<TReq, TRes>(type, payload, timeoutMs?)` returns Promise<TRes>.
 */

/** A free-form identifier for an image flowing through the pipeline. */
export type ImageId = string;

/** A free-form identifier for an audit run / task. */
export type RunId = string;

/** Correlation id generated by MessageBus.request() to wire request/response. */
export type CorrelationId = string;

/**
 * Discriminated union health report.
 *   - `ok: true`  → the agent is ready; `latencyMs` is a self-measured readiness probe.
 *   - `ok: false` → the agent is degraded or unusable; `error` is a human-readable cause.
 */
export type HealthStatus =
  | { ok: true; latencyMs: number }
  | { ok: false; error: string };

/** Static, immutable context handed to an agent at init() time. */
export interface AgentContext {
  /** Optional human-readable run id (orchestrator assigns it). */
  runId?: RunId;
  /** Optional directory the agent may use for caching or scratch. */
  workDir?: string;
  /** Free-form configuration key/value bag (e.g. model name, thresholds). */
  config?: Readonly<Record<string, unknown>>;
}

/** Per-invocation input passed to Agent.run(). */
export interface AgentInput {
  image_id: ImageId;
  /** Image bytes; transport is opaque to the bus. May be a Buffer, base64 string, or remote URL. */
  image?: Buffer | string;
  /** Additional structured context (e.g. upstream OCR text, EXIF, prior layer scores). */
  context?: Readonly<Record<string, unknown>>;
}

/** Per-invocation output produced by Agent.run(). */
export interface AgentOutput {
  image_id: ImageId;
  /** Numeric risk / confidence score in [0, 1] (or any comparable range the agent documents). */
  score: number;
  /** Short human-readable reason / category. */
  reason: string;
  /** Optional extra structured fields the agent wants to publish. */
  details?: Readonly<Record<string, unknown>>;
}

/**
 * The contract every agent (Preprocess, OCR, Text Risk, Vision, Metadata,
 * Porn, Ad, Political, Logo, Risk Fusion) must implement.
 *
 * Declared as `interface` so downstream code can declaration-merge it for
 * agent-specific extensions without rewrites.
 */
export interface Agent {
  readonly id: string;
  readonly version: string;
  init(ctx: AgentContext): Promise<void>;
  run(input: AgentInput): Promise<AgentOutput>;
  healthcheck(): Promise<HealthStatus>;
}

/**
 * Typed envelope carried over the MessageBus.
 *   - `type`    is the channel key (e.g. "agent.preprocess.done").
 *   - `payload` is the user-defined body.
 *   - `correlationId` is set by `request()` and echoed back in the response
 *                    message; absent on ordinary `publish()` fan-out.
 */
export interface AgentMessage<T = unknown> {
  type: string;
  payload: T;
  correlationId?: CorrelationId;
  /** ISO timestamp the message was published. */
  publishedAt: string;
}

/** Subscriber callback signature. */
export type MessageHandler<T = unknown> = (msg: AgentMessage<T>) => void | Promise<void>;

/** Unsubscribe handle returned by MessageBus.subscribe(). */
export type Unsubscribe = () => void;

/**
 * Transport-agnostic message bus contract.
 *
 * Sprint 1 ships a single in-process implementation
 * (`EventEmitterMessageBus` in ./message-bus.ts). A future NATS/Kafka
 * transport can satisfy the same interface without touching agent code.
 */
export interface MessageBus {
  /**
   * Fire-and-forget broadcast. Returns the number of subscribers that received it.
   * The optional `correlationId` is included in the AgentMessage envelope so
   * that `request()` responders can echo it back on `<type>.response`.
   */
  publish<T>(type: string, payload: T, correlationId?: CorrelationId): number;

  /**
   * Subscribe to a message type. The handler may be sync or async.
   * EventEmitter semantics: handlers run in registration order; a slow
   * handler will block later subscribers (see Risks in sprint-contract.md).
   */
  subscribe<T>(type: string, handler: MessageHandler<T>): Unsubscribe;

  /**
   * Request/response round-trip on the bus. Auto-generates a correlation
   * id, publishes a request, awaits a response on `type + ".response"`,
   * and resolves with the responding handler's return value. Rejects on
   * timeout (default 5000 ms) or if the responder throws.
   */
  request<TReq, TRes>(
    type: string,
    payload: TReq,
    timeoutMs?: number,
  ): Promise<TRes>;
}

/** One structured line appended to ./logs/audit_*.log per agent.run() call. */
export interface AuditLogEntry {
  image_id: ImageId;
  agent: string;
  score: number;
  reason: string;
  elapsed_ms: number;
}

// -------------------------------------------------------------------------
// Sprint 2 additions — pipeline orchestrator types.
//
// All additions are append-only. Do NOT redefine the types above.
// `PipelineState`, `PipelineEvent`, and `OrchestratorSlots` are used by
// the new `src/orchestrator/orchestrator.ts` module.
// -------------------------------------------------------------------------

/**
 * The state machine states. Duplicated here as a string-literal union
 * (re-declared from `src/orchestrator/state-machine.ts`) so consumer code
 * that only imports from `@/agents` does not need to take a dependency
 * on the orchestrator module. The orchestrator module's table is the
 * authoritative adjacency; this union is the type-level alias.
 */
export type PipelineStateS2 =
  | "init"
  | "preprocess"
  | "parallel-fan-out"
  | "fan-in"
  | "fusion"
  | "done"
  | "cancelled"
  | "failed";

/**
 * Envelope published on the MessageBus by the orchestrator for every
 * state transition and for terminal events.
 */
export interface PipelineEvent {
  /** The state the event is about. */
  state: PipelineStateS2;
  /** Image id this transition belongs to. */
  image_id: ImageId;
  /** ISO timestamp the event was published. */
  publishedAt: string;
  /** Optional human-readable reason (e.g. cancel reason, error message). */
  reason?: string;
  /** Free-form extra context the subscriber may want. */
  context?: Readonly<Record<string, unknown>>;
}

/**
 * A checkpoint record the orchestrator publishes on
 * `pipeline.checkpoint` and stores in memory for `resume()`. Sprint 2
 * keeps the checkpoint in memory only; Sprint 3+ may add file-backed
 * durability without changing the public surface.
 */
export interface PipelineCheckpoint {
  /** Image id the checkpoint belongs to. */
  image_id: ImageId;
  /** The state the pipeline was last in before pausing/resuming. */
  lastState: PipelineStateS2;
  /** Output of the preprocess agent, if it has run. */
  preprocessOutput?: import("./types.js").AgentOutput;
  /** Output of the three fan-out agents, keyed by slot name. */
  fanOutOutputs?: {
    textRisk?: import("./types.js").AgentOutput;
    vision?: import("./types.js").AgentOutput;
    metadata?: import("./types.js").AgentOutput;
  };
  /** Output of the fusion agent, if it has run. */
  fusionOutput?: import("./types.js").AgentOutput;
  /** ISO timestamp the checkpoint was written. */
  publishedAt: string;
}

/**
 * Named agent slots the orchestrator consumes. Sprint 2 ships 1-line
 * stubs for `preprocess` and `fusion`; epic-2/3/4/6 will replace them.
 * All slots implement the Sprint 1 `Agent` interface, so any concrete
 * agent — stub or real — can be passed in via `init(slots)`.
 */
export interface OrchestratorSlots {
  preprocess: import("./types.js").Agent;
  textRisk: import("./types.js").Agent;
  vision: import("./types.js").Agent;
  metadata: import("./types.js").Agent;
  fusion: import("./types.js").Agent;
}

/** The minimal input the orchestrator's `run()` accepts. */
export interface OrchestratorInput {
  image_id: ImageId;
  /** Optional raw image bytes; threaded through to the metadata agent. */
  image_bytes?: Buffer;
  /** Optional pre-existing OCR text; threaded through to text-risk + vision. */
  ocr_text?: string;
  /** Optional pre-existing bounding boxes from OCR. */
  bboxes?: ReadonlyArray<unknown>;
  /** Optional EXIF summary, threaded through to the vision agent. */
  exif_summary?: Readonly<Record<string, unknown>>;
}

/**
 * Per-layer outputs after a successful pipeline run.
 * Strongly-typed (per sprint-contract.md open question #4) so epic-6's
 * real Risk Fusion has a typed input.
 */
export interface FanInResult {
  preprocess: import("./types.js").AgentOutput;
  textRisk: import("./types.js").AgentOutput;
  vision: import("./types.js").AgentOutput;
  metadata: import("./types.js").AgentOutput;
}

/** Subscriber callback for orchestrator state-change events. */
export type OrchestratorSubscriber = (event: PipelineEvent) => void;

// -------------------------------------------------------------------------
// Sprint 3 additions — Preprocess Agent types.
// All additions are append-only. Do NOT redefine the types above.
// -------------------------------------------------------------------------

/**
 * Richer input shape for the Preprocess Agent. Declared as a local
 * extension of `AgentInput` so the existing `Agent` interface can stay
 * untouched (declaration merging is not required). The agent's
 * `run(input: PreprocessInput)` accepts this shape directly.
 */
export interface PreprocessInput {
  image_id: ImageId;
  /** Raw image bytes; required for MD5/pHash/metadata extraction. */
  image_bytes: Buffer;
  /** Optional upstream context (unused in Sprint 3; reserved for epic-2). */
  context?: Readonly<Record<string, unknown>>;
}

/**
 * Metadata block returned by the Preprocess Agent on the `details`
 * field. The shape is a superset of the `sharp().metadata()` result
 * plus a `source` discriminator so callers can tell sharp from manual.
 */
export interface PreprocessMetadata {
  width?: number;
  height?: number;
  format?: string;
  space?: string;
  channels?: number;
  hasAlpha?: boolean;
  /** Discriminator: "sharp" (real) or "manual" (header parser). */
  source?: string;
  /** Index signature so the shape is assignable to `Record<string, unknown>`. */
  [key: string]: unknown;
}

/**
 * The `details` payload the Preprocess Agent attaches to its
 * `AgentOutput`. The fields are additive — future epics may extend
 * without breaking the SC-1/2/3 contract.
 */
export interface PreprocessOutputDetails {
  width: number;
  height: number;
  format: "png" | "jpeg" | "webp" | "unknown";
  hash: string;
  phash?: string;
  normalized_bytes?: Buffer;
  metadata: PreprocessMetadata;
  /** Which path the agent used for metadata + normalization. */
  fallback: "sharp" | "manual";
  /** Whether the existing image-compressor.ts was actually invoked. */
  image_compressor_used?: boolean;
  /** Error message from image-compressor if it failed (best-effort). */
  image_compressor_error?: string | null;
  /** Set when the blocklist fast-path fired. */
  hit_kind?: "md5" | "phash";
  /** The matched hash (MD5 or pHash) when the blocklist fired. */
  hit_hash?: string;
  /** Index signature so the shape is assignable to `Record<string, unknown>`. */
  [key: string]: unknown;
}

/**
 * Strongly-typed alias for the Preprocess Agent output shape.
 * (The actual return is `AgentOutput`; this alias is for documentation
 * and for downstream consumers that want to narrow `details`.)
 */
export type PreprocessOutput = AgentOutput & {
  details?: PreprocessOutputDetails;
};

/** A single blocklist entry (MD5 or pHash). */
export interface BlocklistEntry {
  hash: string;
  kind: "md5" | "phash";
}

/**
 * Payload of the `pipeline.preprocess.blocklist-hit` bus event.
 * Published on the active MessageBus by the Preprocess Agent when the
 * blocklist fast-path fires.
 */
export interface BlocklistHitEvent {
  image_id: ImageId;
  /** The matched MD5 (when `hit_kind === "md5"`). */
  md5?: string;
  /** The matched pHash (when `hit_kind === "phash"`). */
  phash?: string;
  hit_kind: "md5" | "phash";
  /** ISO timestamp the event was published. */
  publishedAt: string;
}

// -------------------------------------------------------------------------
// Sprint 4 additions — Specialized sub-agents + Risk Fusion types.
// All additions are append-only. Do NOT redefine the types above.
// -------------------------------------------------------------------------

/**
 * The four specialized sub-targets a single image is evaluated against.
 * Discriminator carried on `SpecializedInput.target` and on
 * `SpecializedOutput.details.target`.
 */
export type SpecializedTarget = "porn" | "ad" | "political" | "logo";

/**
 * The richer input shape for any specialized sub-agent.
 * Re-declared here (alongside the local declaration in
 * src/specialized/specialized-types.ts) so consumers that only import
 * from `@/agents` see the type.
 */
export type SpecializedInput = AgentInput & {
  /** Which specialized target this invocation is scoring. */
  target: SpecializedTarget;
};

/**
 * The richer output shape for any specialized sub-agent.
 */
export type SpecializedOutput = AgentOutput & {
  details: {
    target: SpecializedTarget;
    [key: string]: unknown;
  };
};

/**
 * Action enum emitted by the Risk Fusion Agent. The mapping to a
 * score band is configurable via `FUSION_THRESHOLDS` /
 * `configureFusion({ thresholds })`.
 */
export type FusionAction = "PASS" | "REVIEW" | "REJECT";

/**
 * The 7 per-layer score keys. Each layer contributes to the weighted
 * sum per the value of `FUSION_WEIGHTS[k]`.
 */
export type FusionWeights = {
  text_risk: number;
  vision: number;
  metadata: number;
  porn: number;
  ad: number;
  political: number;
  logo: number;
};

/**
 * The two threshold boundaries the Risk Fusion Agent uses to map a
 * weighted sum to an action:
 *   - score >= rejectAt → "REJECT"
 *   - score >= reviewAt → "REVIEW"
 *   - else            → "PASS"
 */
export type FusionThresholds = {
  rejectAt: number;
  reviewAt: number;
};

/**
 * The richer input shape for the Risk Fusion Agent. The `per_layer`
 * record carries the 7 per-layer scores; missing entries default to
 * 0.0 (see `risk-fusion-agent.ts`).
 */
export type FusionInput = AgentInput & {
  context: {
    per_layer: Partial<FusionWeights>;
  };
};

/**
 * The richer output shape for the Risk Fusion Agent.
 */
export type FusionOutput = AgentOutput & {
  details: {
    action: FusionAction;
    per_layer: Readonly<FusionWeights>;
    weights: Readonly<FusionWeights>;
  };
};

/**
 * Declaration-merge interface for the 4 OPTIONAL specialized slots
 * added in Sprint 4. The orchestrator's local slot type widens to
 * `OrchestratorSlots & Partial<SpecializedOrchestratorSlots>`, so
 * the public 5-field shape in `OrchestratorSlots` is preserved
 * (callers from Sprint 1-3 keep compiling) while Sprint 4 callers
 * can opt-in to the 4 new slots.
 *
 * See sprint-contract.md Risks §1 for the deviation rationale.
 */
export interface SpecializedOrchestratorSlots {
  /** Slot for the Porn-Agent (target: "porn"). */
  porn?: import("./types.js").Agent;
  /** Slot for the Ad-Agent (target: "ad"). */
  ad?: import("./types.js").Agent;
  /** Slot for the Political-Agent (target: "political"). */
  political?: import("./types.js").Agent;
  /** Slot for the Logo-Agent (target: "logo"). */
  logo?: import("./types.js").Agent;
}
